name: Translation Sync

description: |
  Sync translation files to and from an s3-compatible remote bucket. This uses
  `@get-bridge/sync-format-message-translations` and thus requires authentication
  with Github Packages.

inputs:
  config:
    required: false
    default: translation-sync.json

runs:
  using: composite
  steps:
    - name: Run @get-bridge/sync-format-message-translations
      shell: bash
      env:
        INPUT_CONFIG: ${{ inputs.config }}
      run: |
        npx @get-bridge/sync-format-message-translations@^2.0.0 sync-translations --config "${INPUT_CONFIG:-TRANSLATION_SYNC_CONFIG}"
